
management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics
  influx:
    metrics:
      export:
        enabled: 'true'
        uri: http://influxdb:8086
        db: springboot
        auto-create-db: 'true'
