{
 "title": "springboot Dashboard",
 "description": "springboot metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Quick Facts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Start Time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "process_start_time",
     "query": "SELECT \"value\" FROM \"process_start_time\" WHERE  $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Process CPU usage",
   "type": "blackmirror1-singlestat-math-panel",
   "description": "The percentage of total system CPU",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "alias": "value",
     "measurement": "process_cpu_usage",
     "query": "SELECT \"value\" FROM \"process_cpu_usage\"  WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" }
     ]
    }
   ]
  },
  {
   "title": "System CPU usage",
   "type": "blackmirror1-singlestat-math-panel",
   "description": "The proportion of the total number of CPUs in the system",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "alias": "value",
     "measurement": "system_cpu_usage",
     "query": "SELECT \"value\" FROM \"system_cpu_usage\" where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" }
     ]
    }
   ]
  },
  {
   "title": "Requests",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Client Error",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "http_server_requests",
     "query": "select sum(count) from http_server_requests where outcome = 'CLIENT_ERROR' and $timeFilter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
      { "condition": "AND", "key": "status", "operator": "=~", "value": "/^$status$/" },
      { "condition": "AND", "key": "uri", "operator": "=~", "value": "/^$uri$/" }
     ]
    },
    {
     "alias": "Success",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(count) from http_server_requests where outcome = 'SUCCESS'  and $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "runtime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "process_uptime",
     "query": "SELECT \"value\" FROM \"process_uptime\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "QPS",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "http_server_requests",
     "query": "SELECT sum(\"count\")  / 60 FROM \"http_server_requests\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 300" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Number of open files",
   "type": "michaeldmoore-annunciator-panel",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "targets": [
    {
     "measurement": "process_files_open",
     "query": "SELECT \"value\" FROM \"process_files_open\" WHERE  $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" }
     ]
    }
   ]
  },
  {
   "title": "System load in the last minute",
   "type": "michaeldmoore-annunciator-panel",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 8 },
   "targets": [
    {
     "measurement": "system_load_average_1m",
     "query": "SELECT \"value\" FROM \"system_load_average_1m\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "michaeldmoore-annunciator-panel",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 8 },
   "targets": [
    {
     "measurement": "jvm_threads_live",
     "query": "SELECT \"value\" FROM \"jvm_threads_live\" WHERE  $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" }
     ]
    }
   ]
  },
  {
   "title": "Request",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  }
 ]
}